### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kakugiki**
Add index(indexName, indexValue). As suggested, I have moved my code here from idb-keyval. Thanks.

### CODE REVIEW

**Comment by jakearchibald** [comment]
Although what you're trying to do fits more into the feature set of this library than `idb-keyval`, I don't think it's worth adding.

Besides, the implementation can just be:

```js
const values = await db.transaction('store-name').objectStore('store-name').index('index-name').getAll();
```

**Comment by kakugiki** [comment]
Thanks for getting back.

Just for the record, you missed the point of the index-value. What I really want to get is not all the records with the same index, but index with certain values. Say, you want to get index-name ('movie') with a value as 'Action', not 'Horror' or anything else. This is the main reason that I was trying to use indexeddb over localStorage.

**Comment by jakearchibald** [comment]
I don't think I missed the point. You can pass the query to `getAll`.

```js
const values = await db.transaction('store-name').objectStore('store-name')
  .index('index-name').getAll(indexValue);
```

**Comment by kakugiki** [comment]
I didn't know that you can pass a parameter to getAll() like that. Thank you for the update, it helps a lot.

**Pull request closed without merging**
