### PR TITLE
check if IDBIndex exists for isomorphic apps

### PR DESCRIPTION
**Pull request by noahehall**
resolves this issue
https://github.com/jakearchibald/idb/issues/17

### CODE REVIEW

**Comment by noahehall** [comment]
renamed, as window does not exist in worker ;)

**Comment by jakearchibald** [comment]
I'm not keen on this PR as it does loads more than solve the issue in question. For instance, it makes a load of global functions.

**Comment by noahehall** [comment]
hmm, what would be your approach to resolve the issue?

**Comment by jakearchibald** [comment]
I wonder if https://github.com/defunctzombie/package-browser-field-spec/blob/master/README.md can be used here

**Comment by noahehall** [comment]
ill try it out tonight after work and report back

**Comment by noahehall** [comment]
hey man sorry for the delay, things have been hectic at work, hoping to get to this this weekend.

**Comment by jakearchibald** [comment]
@noahehall no rush!

**Comment by noahehall** [comment]
closing this pull request, as I opened a new one here: https://github.com/jakearchibald/idb/pull/27

**Pull request closed without merging**
