### PR TITLE
This change is more universally compilable.

### PR DESCRIPTION
**Pull request by tom-huguenard**
Not sure if this works. Not sure what it does. But it allows my code to compile and run, so I submit it might be good. Have a look!
Thanks!

### CODE REVIEW

**Comment by jakearchibald** [comment]
I guess you're targeting a system that doesn't support [object spread](https://github.com/tc39/proposal-object-rest-spread).

To keep the library small, I'm keeping the JavaScript here as modern is possible. Folks can use Babel etc to transpile it down to their taget.

**Comment by tom-huguenard** [comment]
No problem. Can you include instructions on how to transpile your modern code? I am using Babel and configuration documentation is murky at best. I use the spread operator, but one of my dependencies doesn't seem to understand it, so your awesome code is failing as shipped.

**Comment by tom-huguenard** [comment]
And thanks for replying so generously. btw...

**Comment by jakearchibald** [comment]
Which bundler are you using?

**Comment by tom-huguenard** [comment]
nvm. Thanks. I was just trying to suggest how you might update your docs. Peace...

**Comment by jakearchibald** [comment]
oh ok

**Pull request closed without merging**
