### PR TITLE
Automate type-test.ts

### PR DESCRIPTION
**Pull request by NotWoods**
Manually checking the `test/type-test.ts` file for problems is error-prone thanks to our poor human eyes. I added a script that will automate checking that certain lines in the test file have type errors. This also allows for CI to do the checking in the future.

[I threw together a script to scan the output from `tsc` for errors for this project](https://github.com/NotWoods/assert-typescript-errors), but it ended up being big enough to stick in a separate package. Feel free to just copy over the code if you prefer.

### CODE REVIEW

**Comment by jakearchibald** [comment]
I agree that the manual test is bad, but I think I'm going to give https://github.com/Microsoft/dtslint a try.

If it doesn't work out, I'll merge this.

**Comment by jakearchibald** [comment]
…although I'm worried https://github.com/Microsoft/dtslint/issues/57 is going to hit hard.

**Comment by jakearchibald** [comment]
https://github.com/dsherret/conditional-type-checks is another option

**Comment by jakearchibald** [comment]
Actually, the latter seems much simpler and more versatile.

**Comment by jakearchibald** [comment]
My current plan is to merge the type tests with my regular tests.

**Comment by NotWoods** [comment]
Closing since conditional-type-checks seems like a great tool :smile:

**Pull request closed without merging**
